### ISSUE TITLE
TypeError: concat() got an unexpected keyword argument 'axis' from getvector.py

### ISSUE THREAD

**Issue by biswasaveek** [jiexunsee/Simple-Inception-Transfer-Learning#4]
When I run 
`python classifier.py test cat.jpg`

I get the following error:
```
Traceback (most recent call last):
  File "classifier.py", line 127, in <module>
    image_input = getvector(file_name).reshape((1,2048))
  File "{}/Simple-Inception-Transfer-Learning-master/getvector.py", line 36, in getvector
    vector, _ = v3.inception_v3(processed_images, num_classes=1001, is_training=False)
  File "{}/Simple-Inception-Transfer-Learning-master/inception_v3.py", line 481, in inception_v3
    depth_multiplier=depth_multiplier)
  File "{}/Simple-Inception-Transfer-Learning-master/inception_v3.py", line 161, in inception_v3_base
    net = tf.concat(axis=3, values=[branch_0, branch_1, branch_2, branch_3])
TypeError: concat() got an unexpected keyword argument 'axis'
```

Line 36 in getvector.py is:
`vector, _ = v3.inception_v3(processed_images, num_classes=1001, is_training=False)`

**Comment by biswasaveek** [comment]
Has it something to do with tensorflow version. Mine is '0.12.1'

**Comment by jiexunsee** [comment]
Hi biswasaveek 

I think it is due to the tensorflow version, it should work with the newest tensorflow!

**Comment by biswasaveek** [comment]
Yes, updating to the latest version of tensorflow resolves this. 
However, both `python classifier.py test cat.jpg` and `python classifier.py test dog.jpg`
yield the same results:
`It's a cat: 0.00438925763592124, It's a dog: 0.995610773563385`
and the 2048 dimensional vector is also the same for both the images:
`[ 0.17922133  0.04976706  0.22792906 ...,  0.17664079  0.00030257  0.        ]`

@jiexunsee Am I missing something over here?

**Comment by jiexunsee** [comment]
Hmmm, I'm not sure why that would happen. Maybe try running again, making sure the cat.jpg and dog.jpg files are correct?

**Comment by biswasaveek** [comment]
@jiexunsee Yup, they are the ones that are already in the repo. I even tried for other pictures of cats and dogs.. they too are giving the same result.

**Comment by jiexunsee** [comment]
Did you make any edit to the code?

**Comment by biswasaveek** [comment]
Hi @jiexunsee 
You are correct.. my bad.. 
I had uncommented the line `#imagedir = '/home/jiexun/Desktop/Siraj/ImageChallenge/Necessary/train/cat.0.jpg'` in getvector.py and had entered my own file path. Had done it to get the vector representation of a single file. That's why it was always giving the same vector.
Just a small suggestion: The parameter `imagedir` of the `getvector` method can be renamed to `imagefile` as the function fetches the vector representation of a single file rather than a directory.
By the way, very good job apart from that !! Thanks !!

**Comment by jiexunsee** [comment]
Hi @biswasaveek good to know that it works! 

Thanks for the suggestion, I named it `imagedir` as I am passing the path to the image into the `getvector` method!

Thanks too, and all the best :)
